# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaaster', '0002_auto_20160116_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_added',
        ),
    ]
