# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaaster', '0003_auto_20160116_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default=b'images/avatars/no_avatar.jpg', null=True, upload_to=b'images/avatars/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], default=b'M', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
