# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaaster', '0004_auto_20160116_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1, null=True),
        ),
    ]
