# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaaster', '0007_auto_20160116_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagsinreplies',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='tagsinreplies',
            name='tag',
        ),
        migrations.DeleteModel(
            name='TagsInReplies',
        ),
    ]
